version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DoubleVPartners
      POSTGRES_DB: ticketdb
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"